=== Zharell/DAM1/DAM - Año 1 -/Lenguaje de Marcas/Tema 8/Práctica Videoclub/videoclub.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="facturas">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element name="factura" type="factura_type" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="factura_type">
      <xsd:sequence>
        <xsd:element name="datos_cliente" type="datosCliente_type" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="datos_ticket" type="datosTicket_type" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="datosCliente_type">
      <xsd:sequence>
          <xsd:element name="nombre" type="xsd:string" minOccurs="1" maxOccurs="1"/>
          <xsd:element name="apellido1" type="xsd:string" minOccurs="1" maxOccurs="1"/>
          <xsd:element name="apellido2" type="xsd:string" minOccurs="0" maxOccurs="1"/>
          <xsd:element name="dni" type="xsd:string" minOccurs="1" maxOccurs="1"/>
          <xsd:element name="telefono" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
       <xsd:attribute name="id_cliente" type="xsd:ID" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="datosTicket_type">
      <xsd:sequence>
        <xsd:element name="resguardo" type="resguardo_type" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="alquiler" type="alquiler_type" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="compra" type="compra_type" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="resguardo_type">
      <xsd:sequence>
          <xsd:element name="formaPago" type="xsd:string" minOccurs="1" maxOccurs="1"/>
          <xsd:element name="importe" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="alquiler_type">
      <xsd:sequence>
          <xsd:element name="pelicula" type="pelicula_type" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="fecha" type="xsd:string" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="pelicula_type">
      <xsd:sequence>
        <xsd:element name="titulo" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="genero" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="duracion" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="actor" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="idPelicula" type="xsd:ID"/>
    </xsd:complexType>
    <xsd:complexType name="compra_type">
      <xsd:sequence>
        <xsd:element name="video" type="video_type" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="dvd" type="dvd_type" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="video_type">
      <xsd:sequence>
        <xsd:element name="titulo" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="formato" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="rewind" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType></xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="dvd_type">
      <xsd:sequence>
        <xsd:element name="titulo" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="fecha" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="extras" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType></xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Zharell/DAM1/DAM - Año 1 -/Lenguaje de Marcas/Tema 8/Práctica Videoclub/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<facturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:noNamespaceSchemaLocation = "videoclub.xsd">
	
	
	<factura>
		<datos_cliente id_cliente="e1">
			<nombre>Carlos</nombre>
			<apellido1>Lizarran</apellido1>
			<apellido2>gomez</apellido2>
			<dni>1234567x</dni>
			<telefono>666777888</telefono>
		</datos_cliente>
		<datos_ticket>
			<resguardo>
				<formaPago>Efectivo</formaPago>
				<importe>21.00</importe>
			</resguardo>
			<alquiler fecha="21/12/2014">
				<pelicula idPelicula="abcd1234">
					<titulo>El viaje de Chihiro</titulo>
					<genero>Anime</genero>
					<duracion>145min</duracion>
					<actor>Tomoko Yamaguchi</actor>
					<actor>Nobou Maharu</actor>
				</pelicula>
				<pelicula idPelicula="abcd3456">
					<titulo>Crash</titulo>
					<genero>Accion</genero>
					<duracion>170min</duracion>
					<actor>Bruce Willis</actor>
					<actor>Elsa Pataki</actor>
					<actor>Dani Glober</actor>
				</pelicula>
			</alquiler>
			<compra>
				<dvd>
					<titulo>Los Goonies</titulo>
					<fecha>12/03/1983</fecha>
					<extras/>
				</dvd>
      </compra>
		</datos_ticket>
	</factura>
	
	
	<factura>
		<datos_cliente id_cliente="e2">
			<nombre>Laura</nombre>
			<apellido1>Blanco</apellido1>
			<dni>238457284l</dni>
			<telefono>665554443</telefono>
		</datos_cliente>
		<datos_ticket>
			<resguardo>
				<formaPago>Tarjeta</formaPago>
				<importe>12.00</importe>
			</resguardo>
			<compra>
				<video>
					<titulo>Irma la dulce</titulo>
					<formato>VHS</formato>
					<rewind/>
				</video>
				<dvd>
					<titulo>Titanic</titulo>
					<fecha>30/02/2000</fecha>
					<extras/>
				</dvd>
				<video>
					<titulo>Goshtship</titulo>
					<formato>Super8</formato>
					<rewind/>
				</video>
			</compra>
		</datos_ticket>
	</factura>
	
	
</facturas>
